# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bk < Formula
  desc "Bookmark your directory"
  homepage "https://github.com/m-88888888/bk"
  version "0.0.1"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/m-88888888/bk/releases/download/v0.0.1/bk_0.0.1_darwin_x86_64.tar.gz"
    sha256 "45feef89ff4c1ec74a54c810b591162d5a2286c50086a1ebf82c82b3d0408cb2"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/m-88888888/bk/releases/download/v0.0.1/bk_0.0.1_linux_x86_64.tar.gz"
    sha256 "fca979acdf19386af4f7295a4d3674d26797d0021b5ea6f09f3e4af0eda55581"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/m-88888888/bk/releases/download/v0.0.1/bk_0.0.1_linux_arm64.tar.gz"
    sha256 "1faa9e859e80dd4506bb19bd425fffb2b2a8a4f2d3945b6415282b7dbcfa307c"
  end

  def install
    bin.install "bk"
  end
end
